# Generated by Django 4.1 on 2023-11-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogging", "0003_alter_category_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="posts",
        ),
        migrations.AddField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="categories", to="blogging.category"
            ),
        ),
    ]
